networks:
  proxy:
    external: true

services:
  blogAndrewleeFun:
    image: andrewthomaslee/blog.andrewlee.fun:1l05mgkck4viki2ywxc0wghkxnc1d88f
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blogandrewleefun.rule=Host(`blog.andrewlee.fun`)"
      - "traefik.http.services.blogandrewleefun.loadbalancer.server.port=8080"